### PR TITLE
Update EspSparsnasGateway_schem_Nodemcu.png

### PR DESCRIPTION
**Pull request by Naesstrom**
Updated the schematic with a new one that works.

### CODE REVIEW

**Comment by dogmatic69** [comment]
I do not believe ground should be connected directly to the antenna. This link has some more info with various ways to hook it up.

 https://learn.sparkfun.com/tutorials/rfm69hcw-hookup-guide/the-antenna

**Comment by Naesstrom** [comment]
Ah thought I removed that, the schematic is for a edge mounted SMA antenna but I'll remove it and reupload a new one. GND shouldn't be connected to rst permanently neither.

**Comment by dogmatic69** [comment]
Ground should totally be connected to RST. See: https://github.com/bphermansson/EspSparsnasGateway/issues/20

You could just modify this PR, no need to open a new one.

**Comment by Naesstrom** [comment]
@dogmatic69 yes but it should only be pulled low when initiating the radio not all the time as I understand it from Adafruits guide?

> At the top of the sketch you can also set the pinout. The radios will use hardware SPI, but you can select any pins for RFM69_CS (an output), RFM_IRQ (an input) and RFM_RST (an output). RFM_RST is manually used to reset the radio at the beginning of the sketch. RFM_IRQ must be an interrupt-capable pin. Check your board to determine which pins you can use!

**Comment by dogmatic69** [comment]
These additional commits should not be in this PR. You need to make branches for your PR's @Naesstrom

**Comment by Naesstrom** [comment]
Sorry @dogmatic69 still a beginner at GIT could you give me a pointer what you mean?

**Comment by dogmatic69** [comment]
@Naesstrom you have made these changes on `master` branch and now made additional changes which are showing up here. The only changes in the PR should be the image.

You need to create a fork from master and modify that PNG. Once done you can push that branch to github and then edit this PR so that it will merge the new branch with only image changes into master.

**Pull request closed without merging**
