### PR TITLE
Updated information on RF performance tips

### PR DESCRIPTION
**Pull request by tubalainen**
Please commit :)

### CODE REVIEW

**Comment by bphermansson** [comment]
Can you clarify "Keep the wires between the RFM69 module as short as possible"? Between the RFM69 and what?

**Comment by bphermansson** [comment]
Ok good! Have you tried using long wires? Just wondering, even if I'm sure it's best to use as short wires as possible.

**Comment by tubalainen** [comment]
Yes, I tried that and it did not work well.

**Comment by bphermansson** [comment]
Ok fine I'll merge.

**Pull request merged**
